services:
  nginx:
    volumes:
      - ./nginx_prod/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx_prod/ssl:/etc/nginx/ssl:ro
      - ./nginx/certbot:/var/www/certbot:ro

  frontend:
    environment:
      - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL:-https://tuyunai.cn/api/v1}
